#!/usr/bin/python
import sys
import urllib
from os import getcwd

#Prints the current progress when downloading
def Progress(current, blockSize, total):
	percent = int((current*blockSize*100)/total) #Takes number of blocks downloaded multiplies it by size and 100 then divides by total size to get an integer value
	sys.stdout.write("\rPercent Done: %2d%%" % percent)
	sys.stdout.flush()

def downloadFile(type): #downloads the dev and beta crafbukkit versions
	print "Downloading \"craftbukkit-"+type+".jar\" to " + getcwd()
	urllib.urlretrieve("http://dl.bukkit.org/latest-"+type+"/craftbukkit-"+type+".jar", "craftbukkit-"+type+".jar", reporthook=Progress)
	print "\rDone!"

if len(sys.argv)<2:
	print "USAGE: update-bukkit <rel,beta,dev>"
elif sys.argv[1]=="rel": #since the release bukkit format is very different from the other two I just hardcoded it
	print "Downloading \"craftbukkit.jar\" to " + getcwd()
	urllib.urlretrieve("http://dl.bukkit.org/latest-rb/craftbukkit.jar", "craftbukkit.jar", reporthook=Progress)
	print "\rDone!"
elif sys.argv[1]=="dev" or sys.argv[1]=="beta":
	downloadFile(str(sys.argv[1]))
else:
	print "USAGE: update-bukkit <rel,beta,dev>"

